/* eslint-disable import/prefer-default-export */
export const SET_GLOBAL_CURRENT_USER = "SET_GLOBAL_CURRENT_USER"

export const RESET_GLOBAL_STORE_SIGN_OUT = "RESET_GLOBAL_STORE_SIGN_OUT"

export const SET_GLOBAL_SHOW_TOAST = "SET_GLOBAL_SHOW_TOAST"

export const SET_GLOBAL_SHOW_LOADER = "SET_GLOBAL_SHOW_LOADER"

export const SET_GLOBAL_USER_AUTHORIZED = "SET_GLOBAL_USER_AUTHORIZED"
